---

# format:
#  - if it is a release, this is the git commit ID without the "open-release/" prefix. Ex: ironwood.master
#  - if it is not a release, use empty string for master
OPENEDX_RELEASE: ""

# These configuration values must be stored in the user's config.yml.
#MYSQL_ROOT_PASSWORD: "{{ 8|random_string }}"
#OPENEDX_MYSQL_PASSWORD: "{{ 8|random_string }}"
#OPENEDX_SECRET_KEY: "{{ 24|random_string }}"
#ANDROID_OAUTH2_SECRET: "{{ 24|random_string }}"
#ID: "{{ 24|random_string }}"

# This must be defined early
LMS_HOST: "www.myopenedx.com"

# The following are default values
ACTIVATE_CREDENTIALS: false
ACTIVATE_CHROME: false
ACTIVATE_DEVPI: true
ACTIVATE_DISCOVERY: false
ACTIVATE_ECOMMERCE: false
ACTIVATE_FIREFOX: false
ACTIVATE_FORUM: true
ACTIVATE_ELASTICSEARCH: false
#ACTIVATE_HTTPS: false
ACTIVATE_MEMCACHED: false
ACTIVATE_MFE_APP_PUBLISHER: false
ACTIVATE_MFE_GRADEBOOK: false
ACTIVATE_MFE_PROGRAM_CONSOLE: false
ACTIVATE_MYSQL_5_7: false
ACTIVATE_NOTES: false
ACTIVATE_RABBITMQ: false
ACTIVATE_REDIS: false
ACTIVATE_REGISTRAR: false
ACTIVATE_SMTP: true
#CMS_HOST: "studio.{{ LMS_HOST }}"
#CONTACT_EMAIL: "contact@{{ LMS_HOST }}"
#OPENEDX_AWS_ACCESS_KEY: ""
#OPENEDX_AWS_SECRET_ACCESS_KEY: ""
#ANDROID_RELEASE_STORE_PASSWORD: "android store password"
#ANDROID_RELEASE_KEY_PASSWORD: "android release key password"
#ANDROID_RELEASE_KEY_ALIAS: "android release key alias"
#DEV_PROJECT_NAME: "tutor_dev"
DOCKER_IMAGE_OPENEDX: "overhangio/openedx:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_OPENEDX_DEV: "overhangio/openedx-dev:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_FORUM: "overhangio/openedx-forum:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_MEMCACHED: "memcached:1.4.38"
DOCKER_IMAGE_MONGODB: "mongo:3.2.16"
DOCKER_IMAGE_MYSQL: "mysql:5.6.36"
DOCKER_IMAGE_ELASTICSEARCH: "elasticsearch:1.5.2"
DOCKER_IMAGE_NGINX: "nginx:1.13"
DOCKER_IMAGE_RABBITMQ: "rabbitmq:3.6.10-management-alpine"
DOCKER_IMAGE_SMTP: "namshi/smtp:latest"
DOCKER_REGISTRY: "docker.io/"
LOCAL_PROJECT_NAME: "tutor_local"
ELASTICSEARCH_HOST: "elasticsearch"
ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_SCHEME: "http"
ELASTICSEARCH_HEAP_SIZE: 1g
FORUM_HOST: "forum"
#JWT_COMMON_AUDIENCE: "openedx"
#JWT_COMMON_ISSUER: "{% if ACTIVATE_HTTPS %}https{% else %}http{% endif %}://{{ LMS_HOST }}/oauth2"
#JWT_COMMON_SECRET_KEY: "{{ OPENEDX_SECRET_KEY }}"
#K8S_NAMESPACE: "openedx"
#LANGUAGE_CODE: "en"
MEMCACHED_HOST: "memcached"
MEMCACHED_PORT: 11211
MONGODB_HOST: "mongodb"
MONGODB_DATABASE: "openedx"
MONGODB_PORT: 27017
MONGODB_USERNAME: ""
MONGODB_PASSWORD: ""
OPENEDX_CMS_GUNICORN_WORKERS: 2
OPENEDX_LMS_GUNICORN_WORKERS: 2
OPENEDX_MYSQL_DATABASE: "openedx"
OPENEDX_MYSQL_USERNAME: "openedx"
MYSQL_HOST: "mysql"
MYSQL_PORT: 3306
NGINX_HTTP_PORT: 80
NGINX_HTTPS_PORT: 443
PLATFORM_NAME: "My Open edX"
PLUGINS: []
RABBITMQ_HOST: "rabbitmq"
RABBITMQ_USERNAME: ""
RABBITMQ_PASSWORD: ""
SMTP_HOST: "smtp"
SMTP_PORT: 25
SMTP_USERNAME: ""
SMTP_PASSWORD: ""
SMTP_USE_TLS: false
SMTP_USE_SSL: false
#WEB_PROXY: false
